#!/bin/sh -e
# https://romanzolotarev.com/bin/ssg
# copyright 2018-2025 roman zolotarev <hi@romanzolotarev.com>

main() {
	test -n "$1" || usage
	test -n "$2" || usage
	test -n "$3" || usage
	test -n "$4" || usage
	test -d "$1" || no_dir "$1"
	test -d "$2" || no_dir "$2"

	src=$(readlink_f "$1")
	dst=$(readlink_f "$2")

	IGNORE=$(
		if ! test -f "$src/.ssgignore"; then
			printf ' ! -path "*/.*"'
			return
		fi
		while read -r x; do
			test -n "$x" || continue
			printf ' ! -path "*/%s*"' "$x"
		done <"$src/.ssgignore"
	)

	title="$3"
	h_file="$src/_header.html"
	f_file="$src/_footer.html"
	test -f "$f_file" && FOOTER=$(cat "$f_file") && export FOOTER
	if test -f "$h_file"; then
		HEADER=$(cat "$h_file")
		if test -f "$src/style.css"; then
			# Minify CSS using Bun for robustness (handles multi-line comments and whitespace)
			MINIFIED_CSS=$(bun -e "console.log(require('fs').readFileSync('$src/style.css', 'utf8').replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s+/g, ' ').replace(/\s*([{:;,])\s*/g, '\$1').trim())")
			# Inject CSS into the header, replacing the external stylesheet link
			export MINIFIED_CSS
			HEADER=$(echo "$HEADER" | awk '{
				gsub(/<link rel="stylesheet" href="style.css">/, "<style>" ENVIRON["MINIFIED_CSS"] "</style>")
				print
			}')
		fi
		export HEADER
	fi

	list_dirs "$src" | (cd "$src" && cpio -pdu "$dst")

	fs=$(
		if test -f "$dst/.files"; then
			list_affected_files "$src" "$dst/.files"
		else
			list_files "$1"
		fi
	)

	if test -n "$fs"; then
		echo "$fs" | tee "$dst/.files"
		if echo "$fs" | grep -q '\.md$'; then
			if test -x "$(which lowdown 2>/dev/null)"; then
				echo "$fs" | grep '\.md$' | render_md_files_lowdown "$src" "$dst" "$title"
			elif test -x "$(which pandoc 2>/dev/null)"; then
				echo "$fs" | grep '\.md$' | render_md_files_pandoc "$src" "$dst" "$title"
			elif test -x "$(which markdown.pl 2>/dev/null)"; then
				echo "$fs" | grep '\.md$' | render_md_files_markdown_pl "$src" "$dst" "$title"
			else
				echo "couldn't find lowdown, pandoc, nor markdown.pl"
				exit 3
			fi
		fi
		echo "$fs" | grep '\.html$' | render_html_files "$src" "$dst" "$title"
		echo "$fs" | grep -Ev '\.md$|\.html$|^./style\.css$' | (cd "$src" && cpio -pu "$dst")
	fi

	printf '[ssg] ' >&2
	print_status 'file, ' 'files, ' "$fs" >&2
	base_url="$4"
	date=$(date +%Y-%m-%d)
	urls=$(list_pages "$src")
	test -n "$urls" && render_sitemap "$urls" "$base_url" "$date" >"$dst/sitemap.xml"
	print_status 'url' 'urls' "$urls" >&2
	echo >&2
}

readlink_f() {
	file="$1"
	cd "$(dirname "$file")"
	file=$(basename "$file")
	while test -L "$file"; do
		file=$(readlink "$file")
		cd "$(dirname "$file")"
		file=$(basename "$file")
	done
	dir=$(pwd -P)
	echo "$dir/$file"
}

print_status() {
	test -z "$3" && printf 'no %s' "$2" && return
	echo "$3" | awk -v singular="$1" -v plural="$2" 'END {if (NR==1) printf NR " " singular; if (NR>1) printf NR " " plural}'
}

usage() {
	echo "usage: ${0##*/} src dst title base_url" >&2
	exit 1
}

no_dir() {
	echo "${0##*/}: $1: No such directory" >&2
	exit 2
}

list_dirs() {
	cd "$1" && eval "find . -type d ! -name '.' ! -path '*/_*' $IGNORE"
}

list_files() {
	cd "$1" && eval "find . -type f ! -name '.' ! -path '*/_*' $IGNORE"
}

list_dependant_files() {
	e="\\( -name '*.html' -o -name '*.md' -o -name '*.css' -o -name '*.js' \\)"
	cd "$1" && eval "find . -type f ! -name '.' ! -path '*/_*' $IGNORE $e"
}

list_newer_files() {
	cd "$1" && eval "find . -type f ! -name '.' $IGNORE -newer $2"
}

has_partials() {
	grep -qE '^./_.*\.html$|^./_.*\.js$|^./_.*\.css$'
}

list_affected_files() {
	fs=$(list_newer_files "$1" "$2")
	if echo "$fs" | has_partials; then list_dependant_files "$1"; else echo "$fs"; fi
}

render_html_files() {
	while read -r f; do render_html_file "$3" "$f" <"$1/$f" >"$2/$f"; done
}

render_md_files_lowdown() {
	while read -r f; do
		lowdown --html-no-escapehtml --html-no-skiphtml --parse-no-metadata --parse-no-autolink <"$1/$f" | \
			render_html_file "$3" "$f" >"$2/${f%\.md}.html"
	done
}

render_md_files_pandoc() {
	while read -r f; do
		pandoc -f markdown -t html --highlight-style=pygments <"$1/$f" | \
			render_html_file "$3" "$f" >"$2/${f%\.md}.html"
	done
}

render_md_files_markdown_pl() {
	while read -r f; do
		markdown.pl <"$1/$f" | render_html_file "$3" "$f" >"$2/${f%\.md}.html"
	done
}

render_html_file() {
	awk -v title="$1" -v filename="$2" '
	{ body_content = body_content "\n" $0 }
	END {
		body_content = substr(body_content, 2)
		if (body_content ~ /<\/?[Hh][Tt][Mm][Ll]/) { print body_content; exit }
		if (match(body_content, /<[[:space:]]*[Hh]1(>|[[:space:]][^>]*>)/)) {
			t = substr(body_content, RSTART + RLENGTH)
			sub("<[[:space:]]*/[[:space:]]*[Hh]1.*", "", t)
			gsub(/^[[:space:]]*|[[:space:]]$/, "", t)
			if (t) title = t " &mdash; " title
		}

		# Strip leading ./ from filename
		sub(/^\.\//, "", filename)

		# Determine section and page classes
		section = ""
		page_name = filename
		sub(/\.(md|html)$/, "", page_name)
		page_class = "page-" page_name

		if (filename ~ /^(index)\.(md|html)$/) section = "section-general introduction-page"
		else if (filename ~ /^(glossary)\.(md|html)$/) section = "section-general"
		else if (filename ~ /^(getting_started|reactivity|relationships|ordering_logic|server_authoritative)\.(md|html)$/) section = "section-guides"
		else if (filename ~ /^(component_storage|entity_graph|entity_provenance|entity_registry|netcode)\.(md|html)$/) section = "section-reference"
		else if (filename ~ /^example_.*\.(md|html)$/) section = "section-examples"

		n = split(ENVIRON["HEADER"], header, /\n/)
		for (i = 1; i <= n; i++) {
			line = header[i]
			if (match(tolower(line), "<title></title>")) {
				head = substr(line, 1, RSTART - 1)
				tail = substr(line, RSTART + RLENGTH)
				print head "<title>" title "</title>" tail
			} else if (match(tolower(line), "<body(>|[[:space:]][^>]*>)")) {
				full_classes = (section != "" ? section " " : "") page_class
				if (match(line, /class="/)) {
					sub(/class="/, "class=\"" full_classes " ", line)
				} else {
					sub(/<body/, "<body class=\"" full_classes "\"", line)
				}
				print line
			} else print line
		}
		print body_content
		print ENVIRON["FOOTER"]
	}'
}

list_pages() {
	e="\\( -name '*.html' -o -name '*.md' \\)"
	cd "$1" && eval "find . -type f ! -path '*/.*' ! -path '*/_*' $IGNORE $e" | sed 's#^./##;s#.md$#.html#;s#/index.html$#/#'
}

render_sitemap() {
	urls="$1"; base_url="$2"; date="$3"
	echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">"
	echo "$urls" | sed -E 's#^(.*)$#<url><loc>'"$base_url"'/\1</loc><lastmod>'"$date"'</lastmod></url>#'
	echo "</urlset>"
}

main "$@"



